# Project information
site_name:   NaturalSelection.jl
site_description: Infering the presence, strength and effects of natural selection from biological data.
site_author: The BioJulia Organisation
site_url: https://biojulia.github.io/NaturalSelection.jl/

# Repository
repo_url:  https://github.com/BioJulia/NaturalSelection.jl

# Copyright
copyright: Copyright (c) 2017 The BioJulia Organisation

# Documentation and theme
theme: material
docs_dir: 'build'

# Options
extra:
  author:
    github: BioJulia

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

# Extensions
markdown_extensions:
  - extra
  - tables
  - fenced_code
  - codehilite
  - def_list

# Page tree
pages:
- Home: index.md
- dNdS: dNdS.md
- Contributing: contributing.md
